name: Stream Rust

on: [push]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd stream
        cargo build --verbose
    - name: Run tests
      run: |
        cd stream 
        cargo test --verbose
